steps:
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.8/controller.yaml']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-2'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']  
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
