apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdb-env-secrets
  namespace: default
spec:
  encryptedData:
    JWT_TOKEN_SECRET: AgBZ6506N3aV3SdmVlYJiF7Vu9KrDkTW/siLkO/pKUuc/WjJ5eN+hdN5EW9IxkIAUiaoiUufFg+2gyB3E8rUlGfleVo6DwaBHee79EgO+OeJo63/YFHAfCdp/bdKhaiYX5o/pqdFSqh1wAWIW8yOvbsZc85GEH0LzUvzirF+vpiuGhBSHllKz6ei0AA/0og+orIzaBUW+EiWa83vZzHiibU4nPEIHVPFAiBrD94iIm1TbyU/sBSt3IUo5E4zCCAabNRcn7qLKvgEXdtWYvXK+vcPntNyKgvX9k8qY3HOweej3c0hbpjpse9aOwihD5stND80/9fc265Ri0kxzwFnMvnBTwdarS2js6+z4vpVVT6vVDJ+PCn4vweRQP6HVZU5OUAHNWOd6x5jWSG5spVU/qxHcr7ebj1hYW0XObguZ22yoUN9/D1FwZ6WSbq8PKq2X/jUW2UMu/2+ZYqMCX4rDL/ny3T8IBBV+CG4/q5J2w+g1Wk7U4/pQIHTD/AuPEk099IlbQ9VRhGJjO6IJxhoB4dCB6vdUAPdgDwxJPFmIu+opYwSIg7On9hrEwKT6QYTqlwNBJTOf78hfNMvBtfhK6ZYiHR15h1w53ObBPQeKW28LI5bJ/gtsbctHV1ELpQ2rlV/WClp3PFSwz28KdZ47xM/VULmN/+4b4wk9LOGO/2ngQZxjpGq6bdiQhA4kwoa5orCDWc4+R88
    OMDB_API_KEY: AgAj9Dbn0NNTz9L3Ip+kwjB9k5u4IjKfWjK22ewXBBhXvlAqvxb2Hdo81AsK5Z1Z/yFkZoh93ewr6kgnfPr74MwtNdFwqzVMJVy5y3DphKCNRcDo1U9O/UEVshs599NYZgzu83v6ZTovbyyhcLVy/QVLH7yOO/Krp5GgLD/k+vKIJCpaZ7Jh8wTwGCwChqsSavyCxklqwUG41QBrC7S5tDM1te/qDhM5czJl73OQw0pujmFVOoHFB64mERPIJbd7X2TaVLWYFG+anyoxOe0w24amOwlosdRS33zLyKPsKkMNB2EmDEBfqPkeZ2/C4L/9BGFsDXPZUvPidfTMCGmakrfjodH2qZJS10D/euuHBgmeblKVZf+zTZmYlBoRqw4d3Dh//IXCypV89mkV+pmqtLIMKY06AgJTBj1WSW4vj0ncO/0IvnRGNE+Qm//hagbmdnSLzriYeRjGpN++WKWFW3LAi+zqCIjsMHRzEUhJo9sSQMh+b1H4t9EuP9LTZUDGjGQmJuLKIBIQHl0jru3KZGyPszLANvAJdx1Mc8xLrp5x+DgHydCDK0Z1MMhi/EE+fbFa9NR8niBzK5TjAxPsI20x40AWigkntiDpR/4V7kfssf+WW3ZU+I6sBEF/vy74WbVXoXTj1v3WJIZdiasLNkQCRkqu3mnBH+fHQWEy7Y/BQSlyQ8Vbsqf2SVOG0dSc9154OuUhjWGDFw==
  template:
    metadata:
      creationTimestamp: null
      name: imdb-env-secrets
      namespace: default
    type: Opaque
status: {}

