apiVersion: v1
kind: ConfigMap
metadata:
  name: imdb-env-configmap
data:
  HTTP_PORT: "4444"
  DB_URL: mongodb://mongodb:27017
  DB_NAME: omdb
  ZIPKIN_ENDPOINT: http://zipkin-service:9411
  OMDB_URL: http://www.omdbapi.com/
  OMDB_POSTER_URL: http://img.omdbapi.com/
  JWT_VALIDATION: "true"
  