apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-env-secrets
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCw9XBLfc7PZwX+5ZtUOiHDgdW7D8Zg5ypywcApHwj2czD8eZqAuCwVrn7DwmO5WKhHvmCJhiUV+6qbb0Wz4SqYeyinpaPnl1xvHTc4XkDjqLtGzKtzqMa8G3phrGHlTFZ3t8xdENqWZe4FoXi5/AxiKKEQ9LmZKnoD/ZJnhimV333jhhjbk4G+/OO9Gk/+HyzIBaJAnpuuSKiJUmdEYHiex9jZoozKbFlVbEacUPnnc9hR2MNwAReEwsx53u2tFYIh6vkXGSZ6WZ2uNDr6hCcI3PNeSAa2pBZCieqk07U/wXqHTxcpsvyWvDdVir5CVvcO/m0Q1JPL9xJSWxJ8ymhvVcacJwUrX+xJhFYf/6xcyEYvcEa5cErWDxXFe0Oq1SuSgDBD2Hznhgz/wcc8b0gLfvqyKA4R2fOjROJ1TpdUobMz9vkpOy+ust/+tI9cU141n/mimfj8hW04Onh2sazTu1Vtn8efYBvoOEq1mshmjeh6X+mmjFhH8GBqSEAT/Y4HY7r1KTrVW8xi1rUA/Jwnfe1nbS29ihzOU5FKd4RBXbX3J3RR3PAhEmUtIIY1IeFG48L8DdL6ZAE3u1NUJMrsPO0ynXDbHmoOcaQQUvPt7c3sJ6DlheAirE39q64TR3lqLY9TfekMNRsvi07GQWM2QZ0FYsi40YV5ajGSEdITSELxak0rxTRUf6NBwWgFP1EEFdmZxBk=
    POSTGRES_USER: AgCTr/Jq+dIn9J2SGiuFirRT36bc/pVTVp5daGzGxUTntEo2mURRhWfzByrJCY9BgPI8FwUJf4rrHQRy3BVBlryR79DQEbgXE7/EzXwlcPUiFMLdlmdnI/4cVKVR87aHqfeGavlFWjA31J56zWZFgE/EgsJVt+2Hz6oGM2bpfDWaRjMEe+87YqiCxH80nOTy1cMcTK0KIBW5XcCAnIq3vvPjMHYXgFUJmtS/FmY0PoDswXSbRDeJQCSdHmxG8HzwljjCBmsMaLRWoRqX+WwWyyBI0AYqzJMttBpyHU3/TagtawE9lu996zZd5fOkDK2ZlTEHz2Brh/K/49Oi61y5QemBFHAZ4Q7Z0pHu+iXTA7RKsRBtnKmdgAZ4gRH39JcTThxaiWcP1EG2uRS6XRIbxdcV8JMieIj5CZ3RCQKt5nXDtFAS5VxedGhKg6V/Yqy1ac6i9UuE5FtOWgUIjucgNsfYq/Xk2Q4WqDbJbqSI1Kp0UjtwD1qSIv4jdCRO0vaj6GWRalW2/33a+hVnDrfgGwnVZdKyES8UHaLAyZyTMMGTCkTGelQkYyTzYHfQhQ3f7MNH6pZ7ii0IQTXL3MGdduHCxCrPo7Soai7x9fxbiR54DeoncgE2R0ikT0nRl/SIIdaPbXzjQOVL49x3QX4KGD3Lkr2pwaADUUjfFT7U7HKb4vn4Gk+gHb75iJCpRRJhAVrV5CcLFDI=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-env-secrets
      namespace: default
    type: Opaque
status: {}

