apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-env-secrets
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBF8l4ZzlaVB6qG4INvTmUCY9VjsgCI8Jn0ivL4eXDL8iDu1ZszaMvnJ0Xr2wKsch+SuOL/JPNmLamcf/r1XxIP718Og4hrWsRSATekLqXUfQ3mKUmgSnIIgV1eZV9aI7yIeO3eXeMp5RInQJydhl1YMwirLyqYTPyP7EX4VHHvcGWduqHDHSOrMByiy+Sv/cgBJtOzUhWR7aHzMYvHnoqGqGCEFcR6zENhdFaRLjfpXxbB3ETbk9eUGNywlB3bypC0vn3FMAqNNEirNygGcuXtWLXkfuSXD+5X2p0mDt7ILSbssVSsg5Ziw5Z+qjETX2V7abdvwduR9JFTnr2cT3jiLvT1pPZoWRrTegVDq53RhdTaGF9MIO7Gg0DI4C/ohYLoKu1zOyqTy0oIy0rPalR+d570TsnPH0dFXXGcmKLnJCbnBh2h+VUMyzwjWq3b7D3VvBBVchcrzQg7wWoaIUSLi6nXlTqHBMke8Lp2358teIl3SpZ7gRUDkZWm87srQAVSkz/4jd2rMXo9IZh7odVnII3V/VIgkPWlpFSWuN7udjdECKrQq5sJ8erTstBEg5TGO/E60a6HkKQVxQtykr/X5Vy1sfr3cXFGTm4z/cNhe/JDM1+Vlc/6vECt8ihlAwl1r8vmOaobILNQ75YiWluaAjaRWm6VAZYcnJQY0PzOh/qtn9kOOPB3kZJcBTvFi0GgFJW2/sE=
    POSTGRES_USER: AgBNqQy3OGhGzsNCcY1vuryb+mWr8/dXh8RzDyUpfFYBhIrL5WG646Eoc2rP+xHfDJinHvH2gRAbQvCbv6Ht8p//nl/lCJVoF0pZUFgjKaoBduzyqXlxsXYrduobWMAOZBwZwTM2S7kCg6vi6tVPaYyx/eBorBK7qrjoIJkQT5cEhOIGzjYPvzUSnyNqNhUbcqTRCAZgjQxGNVLG4SaxnWVrGCjtgul7fshtNCEwQNr+H3PZMoqkhERDbmMDPDMuJpnp5loiXCrxECS2F8QMG4+HynZqC36kxH9QrghY1LPKkrCN8RFZrchXk4rqsPMyP/BxqQ5wdJJ/RGAtyBfbvDg4iBajw0wL5JiLFopDKC3pHrBSpgRDRxr/eE78/ToXobfmvLvoJw71om+i0eXU5rnAOTcb/pyuhtaZLRSKhKkzCgNWYQoVJi8RcnpRS/+XbiEhSPkg1Xd2R3YBixKPVKae6+bWhWLULapjNroSRDAh7v/N0xUGbf7wXCQwTLmY6eN1iIr5PwZcM5wMKZpAoLfoYwtilyG1ay4a/gAIlmAm7FSTVf2Jogx7u+ZMp9i8JergOZbHssIDC+vT0lLTV+butQnQVB+FbcdbNor/gku4l/ew0rEX2ATJEKBYAM9Pl7UnjknjyTWWrVXjabZWOXo0bhtE3QfBkaILQ0fGfNdRTLA7zJpVRRTtUN6OnkQOYx34sgr46+8=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-env-secrets
      namespace: default
    type: Opaque
status: {}

