apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-env-secrets
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCAaFDzEYScdWeXmLmmzdzRzjKHbD02Ud+W4Lux3DxxFCFT1J1c+yM9uVTdLYMKRpLjpLz3ZjF3hWZtkEj7DaQ0/7C2CtBqq+/fNS3Q4AqTWKjTOQoeYLKUBippH8TRjPkY0dasPTSyR/EyfIxIJCAcCb+zhC44eiJEeAIshgKmOIut2UZ0cpWnGQyJN5ytVvTARQk2JU7ykhQR+nDBTwv2jA2AXx7M8/v1s3hqaTKt7T3wf5qi+uvRitUXIScTyXLI/bCeaN/+gicPbusfRg94XiuI8cEOm/D1bOaGQxQ+cAvcTd5B1IG/ybBzUaNPBqSMp5SYR/KU3anUvYTflCWJX8OWhyDPOOjMUhSeNHa8oLkapbMs26S/bkC7O9rvyONRnaJVmeAZ7OiGlyp7WLcNbSso/pESB9+JMFskc25jMQG32NFDdUhVkCUg2998h0WH5urpr8q1t9kxC9ec1HtD2q5S9LOxUcJ4qZRbM+7/Ck62DXEtAaA/0ul+ympzUSBVocDEnyamjiyL0fHUeHAYrP95thn9bCL+DO4lr+aMkmh9EYSBPrrObL1wSApXb4WZ7An02rSgD1cif8I7GOmT4SYJKeTFVCqDdoVYUSlHozwSODZ70VGE98PzrDF+Ij3voKTYu3ZPa3miP/ElsDWfqwUosaiKZ/IN7HsQYqhNv4NW4RZGmLykGNyZ5Lu9rpM1JL/pyy0=
    POSTGRES_USER: AgAdELSl2qwvQqD3OIgFKZKf0p24a5xQYR+fXc7rYDDNLhyQ8u8ruojlqgYA1T2gQr4i6vbUpxs53+THAQxSzofp75qILCUzkdARgyLt7ba41MmN+x/g1rqujquRwLcUmz1pEHzLcBlR71Xe86nwZp+c9rDYxSC4FQjCeXOwGPeP4h+ToZ9r1b//ThgktHBAE1Aasfpu+wXyZZu0RNpUFNgfPM2aDYm2qzEfUYnrh8quaXEhC+IK3Uy7lMSAGFuzBd/V2bNqN+VKsGYXEcEp3sJuusdg0Yv8PxvaMvGkrjOmgT4g4/5Tycn1zpJjPiFsRJzy7PvbAF3z3rsyHR9RHvtneokDNoUZ7hRVth0DsONg27+2AlfZmK1ddxcxE0QQc1I3Jr4QjQniy3uDdNAfrwXVOYxVhkZKT8gDhEtgB3wfwxA9KgTJnk+27CHyOHH2bwwqabproLk0Y6R3IEkBIYdcXqrYOoyxsM91lA7dLmyOwazbJ9oZUIXdoYdXo0nPITCu4dYGX9tULHSTch5c2NHj0c4aR+jWGtSXKAUtCACHSh3svonoUTyBpuKkuJfyysFkx5mcrhB4gUNHw4yAjuz3cFy8U/TCHGROndsi+gvDq3WGvuBu0WJpK96JMcx0V7zTJU0k3mg4Xy8lvV/OCmt9ELzMs95EYuU8nDWnFbweVfVw59vj0G4DLhIDFI74mPyfnD628C4=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-env-secrets
      namespace: default
    type: Opaque
status: {}

