apiVersion: v1
kind: ConfigMap
metadata:
  name: user-env-configmap
data:
  DB_URL: postgres://pramod:pramod@postgres-service/bpm?sslmode=disable
  JWT_EXPIRE_TIME: '1'
  HTTP_PORT: '8089'
  APP_SENDER_MAIL_ID: auth.service@app.com
  ZIPKIN_SERVICE_NAME: authservice
  ZIPKIN_REPORTER: http://zipkin-service:9411/api/v2/spans
  ZIPKIN_ENDPOINT: zipkin-service:5454 
  ADMIN_EMAIL: abc@gmail.com
  ADMIN_PASSWORD: bbb

  