// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_service/authpb/auth.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenValidateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValidateRequest) Reset()         { *m = TokenValidateRequest{} }
func (m *TokenValidateRequest) String() string { return proto.CompactTextString(m) }
func (*TokenValidateRequest) ProtoMessage()    {}
func (*TokenValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec21d9ee93e05c1, []int{0}
}

func (m *TokenValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidateRequest.Unmarshal(m, b)
}
func (m *TokenValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidateRequest.Marshal(b, m, deterministic)
}
func (m *TokenValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidateRequest.Merge(m, src)
}
func (m *TokenValidateRequest) XXX_Size() int {
	return xxx_messageInfo_TokenValidateRequest.Size(m)
}
func (m *TokenValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidateRequest proto.InternalMessageInfo

func (m *TokenValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenValidateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValidateResponse) Reset()         { *m = TokenValidateResponse{} }
func (m *TokenValidateResponse) String() string { return proto.CompactTextString(m) }
func (*TokenValidateResponse) ProtoMessage()    {}
func (*TokenValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eec21d9ee93e05c1, []int{1}
}

func (m *TokenValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidateResponse.Unmarshal(m, b)
}
func (m *TokenValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidateResponse.Marshal(b, m, deterministic)
}
func (m *TokenValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidateResponse.Merge(m, src)
}
func (m *TokenValidateResponse) XXX_Size() int {
	return xxx_messageInfo_TokenValidateResponse.Size(m)
}
func (m *TokenValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidateResponse proto.InternalMessageInfo

func (m *TokenValidateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TokenValidateResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenValidateRequest)(nil), "grpc_service.tokenValidateRequest")
	proto.RegisterType((*TokenValidateResponse)(nil), "grpc_service.tokenValidateResponse")
}

func init() {
	proto.RegisterFile("grpc_service/authpb/auth.proto", fileDescriptor_eec21d9ee93e05c1)
}

var fileDescriptor_eec21d9ee93e05c1 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2f, 0x2a, 0x48,
	0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x2c, 0x2d, 0xc9, 0x28, 0x48, 0x02,
	0x53, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0xc8, 0xf2, 0x4a, 0x3a, 0x5c, 0x22, 0x25,
	0xf9, 0xd9, 0xa9, 0x79, 0x61, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0xa9, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x60, 0x71, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x08, 0x47, 0xc9, 0x9d, 0x4b, 0x14, 0x4d, 0x75, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04,
	0x17, 0x7b, 0x70, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31, 0x58, 0x03, 0x47, 0x10, 0x8c, 0x0b, 0x32,
	0xc8, 0x35, 0x37, 0x31, 0x33, 0x47, 0x82, 0x09, 0x62, 0x10, 0x98, 0x63, 0x94, 0xc2, 0xc5, 0xed,
	0x58, 0x5a, 0x92, 0x11, 0x0c, 0x71, 0x85, 0x50, 0x28, 0x17, 0x07, 0xcc, 0x48, 0x21, 0x25, 0x3d,
	0x64, 0x07, 0xea, 0x61, 0x73, 0x9d, 0x94, 0x32, 0x5e, 0x35, 0x10, 0x37, 0x29, 0x31, 0x38, 0x71,
	0x44, 0xb1, 0x41, 0xfc, 0x9f, 0xc4, 0x06, 0xf6, 0xbb, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0xce, 0xc2, 0x53, 0x1d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Validate(ctx context.Context, in *TokenValidateRequest, opts ...grpc.CallOption) (*TokenValidateResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Validate(ctx context.Context, in *TokenValidateRequest, opts ...grpc.CallOption) (*TokenValidateResponse, error) {
	out := new(TokenValidateResponse)
	err := c.cc.Invoke(ctx, "/grpc_service.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Validate(context.Context, *TokenValidateRequest) (*TokenValidateResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *TokenValidateRequest) (*TokenValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_service.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*TokenValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_service/authpb/auth.proto",
}
